# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

#Use R
language: r
cache:
  - packages
warnings_are_errors: false
r_build_args: "--no-build-vignettes --no-manual"
r_check_args: "--no-build-vignettes --no-manual --ignore-vignettes"
dist: xenial
os: linux

# environment variables set for all builds
env:
  global:
    - BIOC_USE_DEVEL="FALSE" ## Use the current release version

addons:
  apt:
    packages:
      - libnetcdf-dev # for mzR, a dependency of xcms
      - netcdf-bin # for ncdf4, a dependency of mzR
      - ghostscript # for checking size of PDFs

r:
 - oldrel
 - release
 - devel

r_github_packages:
 - jmosl01/lcmsfishdata

install:
 - Rscript --verbose -e 'deps <- remotes::dev_package_deps(dependencies = NA);remotes::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing:\n", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'

after_success:
 - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
