# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: r
sudo: required
cache: packages

before_install:
 - sudo apt-get update
 - sudo apt-get install libnetcdf-dev netcdf-bin

bioc_packages:
 - BiocParallel
 - CAMERA
 - xcms
