# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: r
cache: packages
sudo: false
warnings_are_errors: false

addons:
  apt:
    packages:
      - libnetcdf-dev # for mzR, a dependency of xcms
      - netcdf-bin # for ncdf4, a dependency of mzR

bioc_packages:
 - BiocParallel
 - BiocStyle
 - CAMERA
 - xcms

 after_success:
    - Rscript -e 'covr::codecov()'
