# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: r
cache: packages
sudo: false

addons:
  apt:
    packages:
      - libnetcdf-dev # for mzR, a dependency of xcms

bioc_packages:
 - BiocParallel
 - CAMERA
 - xcms
